#!/bin/sh

SCRIPTS_PATH="/usr/lib/dipicar/scripts/installation"

#Running of the configuration script
${SCRIPTS_PATH}/services_config.py

#Generation of app creds
${SCRIPTS_PATH}/ssl_keys_gen.py

#Add cron job for ssl key generation
ln -s ${SCRIPTS_PATH}/ssl_keys_gen.py /etc/cron.monthly/ssl_keys_gen.py

exit 0
