#!/bin/sh

#cleaning the access point interface
iw dev uap0 del

#removal of cron job
#rm /etc/cron.monthly/ssl_keys_gen.py

#removal of log, data and lib folders
rm -rf /var/log/dipicar /var/local/dipicar /usr/lib/dipicar

exit 0
