#!/bin/sh

#cleaning the access point interface
iw dev uap0 del

#removal of cron job
rm /etc/cron.monthly/ssl_keys_gen.py

#removal of log and data folders
rm -rf /var/log/dipicar /var/dipicar

exit 0
